version: 0.2
phases:
  install:
    commands:
      - nohup /usr/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=vfs &
      - timeout 15 sh -c "until docker info; do sleep 1; done"
  pre_build:
    commands:
      - aws --version
      - java --version
      - docker --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_ID=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - VERSION=$COMMIT_ID
      - if [[ $CODEBUILD_WEBHOOK_HEAD_REF == refs/tags/* ]]; then export VERSION=${CODEBUILD_WEBHOOK_HEAD_REF#refs/tags/}; fi
      - echo "$VERSION"
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:$VERSION
      - printf '[{"name":"public-website","imageUri":"%s"}]' $REPOSITORY_URI:$VERSION > imagedef.json
artifacts:
  files:
    - imagedef.json