server:
  port: 8091

logging:
  level:
    org.elpuentesearcy: TRACE

trello:
  api:
    baseUrl: https://api.trello.com/1/
    key: ${EL_PUENTE_WEBAPP_TRELLO_API_KEY}
    token: ${EL_PUENTE_WEBAPP_TRELLO_API_TOKEN}
  approvalListId: 5d93720df8af5683824ac6bf
  approvedListId: 5d9373776cd8888e4d4f5977

org.elpuentesearcy:
  version: @project.version@
  prodMode: false
  domain: localhost
  email: office@elpuentesearcy.org
  phone: 5018279944
#  officeHoursWeekday: 1:30pm - 5:30pm
#  officeHoursWeekend: 10:00am - 4:00pm
  physicalAddress:
    - 904 North Main Street
    - Searcy, AR 72143
  mailingAddress:
    - P.O. Box 8046
    - Searcy, AR 72145
  facebookUrl: https://www.facebook.com/profile.php?id=100094143615668
  twitterUrl:
  instagramUrl: https://www.instagram.com/el.puente
  giveLivelyUrl: https://secure.givelively.org/donate/el-puente-hispanic-services-center
  salsaCompetitionSignupUrl: https://docs.google.com/forms/d/e/1FAIpQLSe1X-sTwzfxQCi8GXluDAtPHG6o_uZGpKo_YX74dfyokr1d2w/viewform?usp=sf_link
  salsaCompetitionRulesDownload: SalsaCompetitionRules
  gardenTour2021Url: https://secure.givelively.org/event/el-puente-hispanic-services-center/garden-tour-of-searcy-2021
  volunteerFormDownload: ElPuenteVolunteerForm
  cashtag: $ElPuenteSearcy
  volunteerFormUrl_en: https://forms.gle/Xbez1S4d6gyg7cQB6
  volunteerFormUrl_es: https://forms.gle/kTxkKQewzYN4kkgq5
  hispanicHeritageMonthCelebrationDinnerTicketsUrl: https://secure.givelively.org/event/el-puente-hispanic-services-center/hispanic-heritage-month-celebration-dinner-2022
  showGivingTuesdayWidgetStart: '2019-10-31'
  showGivingTuesdayWidgetEnd: '2019-12-02'
  showHispanicHeritageMonthCelebrationDinnerStart: '2022-09-14'
  showHispanicHeritageMonthCelebrationDinnerEnd: '2022-10-14'
  google:
    analytics:
      trackingId:
    maps:
      apiKey: ${EL_PUENTE_WEBAPP_GOOGLE_MAPS_API_KEY}
  board:
    - name: Jay Simpson
      title:
        en: President
        es: Presidente
      description:
        en: Senior Associate Director of Financial Aid Services<br/><strong>Harding University</strong>
    - name: Larry Wilks
      title:
        en: Vice President
        es: Vicepresidente
      description:
        en: Retired<br/><strong>U.S. Immigration Service</strong>
    - name: Jaclyn Seiders
      title:
        en: Secretary
        es: Sectretaria
      description:
        en: ESOL and Migrant Coordinator<br/><strong>Searcy Public Schools</strong>
    - name: Mary Kathryn Lochala
      title:
        en: Treasurer
        es: Tesorera
      description:
        en:
    - name: Tity Abbud
      title:
        en:
      description:
        en: Community Advocate
    - name: Logan Albright
      title:
        en:
      description:
        en: Community Liaison<br/><strong>ARcare</strong>
    - name: Dr. Roddy Lochala
      title:
        en:
      description:
        en: Chief Medical Officer<br/><strong>Unity Health</strong>
  staff:
    - name: Ruth Simpson
      title:
        en: Executive Director
        es: Directora Ejecutiva
      description:
        en:
      abice-certified: true
    - name: Corinne Aréchiga
      title:
        en: Assistant Director
        es: Asistente a la Directora
      description:
        en:
      abice-certified: true
    - name: Laticia Harris
      title:
        en: English Teacher
        es: Maestra de Inglés
      description:
        en:
    - name: Guillermo Hernandez
      title:
        en: Legal Advisor
        es: Consejero Legal
      description:
        en: