server:
  port: 8091

logging:
  level:
    org.elpuentesearcy: TRACE

org.elpuentesearcy:
  version: @project.version@
  isTestMode: true
  siteChanges:
    - Added volunteer form download at the top and bottom of the <a href="/involvement">Get Involved</a> page.
    - The volunteer form downloads as a .PDF instead of .docx, in case users aren't running on Windows.
    - Also on the <a href="/involvement">Get Involved</a> page, a Give Lively donation widget has been embedded.
    - The Give Lively campaign has also been linked to from the list of donation options.
  domain: localhost
  email: office@elpuentesearcy.org
  phone: 5018279944
  officeHoursWeekday: 1:30pm - 5:30pm
  officeHoursWeekend: 10:00am - 4:00pm
  physicalAddress:
    - 904 North Main Street
    - Searcy, AR 72143
  mailingAddress:
    - P.O. Box 8046
    - Searcy, AR 72145
  facebookUrl: https://www.facebook.com/elpuentesearcy/
  twitterUrl:
  instagramUrl: https://www.instagram.com/el.puente
  amazonSmileUrl: https://smile.amazon.com/ch/83-3832275?fbclid=IwAR02gUtFEfDNnqZPOeibD8RSJC_jbKuWXJB6eaQ4H_3i4cpL_Fo3-8W6fuY
  giveLivelyUrl: https://secure.givelively.org/donate/el-puente-hispanic-services-center/website-donations
  google:
    analytics:
      trackingId:
    maps:
      apiKey: AIzaSyAUs1B95NJzFcSpf2An9EDWfKCrDyHlrwQ
  board:
    -
      name: Jay Simpson
      title:
        en: President
        es: Presidente
      description:
        en: Senior Associate Director of Financial Aid Services<br/><strong>Harding University</strong>
    -
      name: Larry Wilks
      title:
        en: Vice President
        es: Vicepresidente
      description:
        en: Chaplain<br/><strong>Harding Place</strong>
    -
      name: Jaclyn Seiders
      title:
        en: Secretary/Treasurer
        es: Sectretaria-Tesorera
      description:
        en: Literacy Coach/ESOL Coordinator<br/><strong>Searcy Public Schools</strong>
    -
      name: Tity Abbud
      title:
        en:
      description:
        en: Community Advocate
    -
      name: Logan Russell
      title:
        en:
      description:
        en: Community Liaison<br/><strong>ARCare</strong>
    -
      name: Dr. Roddy Lochala
      title:
        en:
      description:
        en: Family Medicine Residency Associate Program Director<br/><strong>Unity Health</strong>
  staff:
    - name: Ruth Simpson
      title:
        en: Executive Director
        es: Directora Ejecutiva
      description:
        en:
    - name: Guillermo Hernandez
      title:
        en: Legal Advisor
        es: Consejero Legal
      description:
        en: