org:
  elpuentesearcy:
    aws:
      region: ${AWS_REGION}
      codepipeline:
        pipeline-name: ${CODEPIPELINE_PIPELINE_NAME:public-website-pipeline}
        stage-name: ${CODEPIPELINE_STAGE_NAME:Deploy}
        action-name: ${CODEPIPELINE_ACTION_NAME:ApproveProdDeployment}