server:
  port: 8091

logging:
  level:
    org.elpuentesearcy: TRACE

org.elpuentesearcy:
  version: @project.version@
  isTestMode: true
  siteChanges:
    - Made the navigation bar shrink and stick to the top of the page when you scroll down.
    - Added a banner to the <a href="/">home page</a>.
    - Added a carousel of images from the Ribbon Cutting Ceremony (please make sure all of the images are okay to use - you can use the left/right arrows to scroll through them quickly).
    - Added office hours to the <a href="/contact">contact us page</a>.
  domain: localhost
  email: office@elpuentesearcy.org
  phone: 5018279944
  officeHoursWeekday: 1:30 - 5:30
  officeHoursWeekend: 10:00 - 4:00
  physicalAddress:
    - 904 North Main Street
    - Searcy, AR 72143
  mailingAddress:
    - P.O. Box 8046
    - Searcy, AR 72145
  facebookUrl: https://www.facebook.com/elpuentesearcy/
  twitterUrl:
  google:
    analytics:
      trackingId:
    maps:
      apiKey: AIzaSyAUs1B95NJzFcSpf2An9EDWfKCrDyHlrwQ
  board:
    -
      name: Jay Simpson
      title:
        en: President
        es: El Presidente
      description:
        en: Senior Associate Director of Financial Aid Services<br/><strong>Harding University</strong>
    -
      name: Larry Wilks
      title:
        en: Vice President
        es: El Vicepresidente
      description:
        en: Chaplain<br/><strong>Harding Place</strong>
    -
      name: Jaclyn Seiders
      title:
        en: Secretary/Treasurer
        es: La Sectretaria-Tesorera
      description:
        en: Literacy Coach/ESOL Coordinator<br/><strong>Searcy Public Schools</strong>
    -
      name: Guillermo Hernandez
      title:
        en:
      description:
        en: Immigration Attorney<br/><strong>Hernandez Law Firm</strong>
    -
      name: Tity Abbud
      title:
        en:
      description:
        en: Community Advocate
    -
      name: Logan Russell
      title:
        en:
      description:
        en: Community Liaison<br/><strong>ARCare</strong>
    -
      name: Dr. Roddy Lochala
      title:
        en:
      description:
        en: Family Medicine Residency Associate Program Director<br/><strong>Unity Health</strong>
  staff:
    - name: Ruth Simpson
      title:
        en: Executive Director
        es: La Directora Ejecutiva
      description:
        en: