server:
  port: 8091

logging:
  level:
    org.elpuentesearcy: TRACE

org.elpuentesearcy:
  version: @project.version@
  isTestMode: true
  siteChanges:
    - Embedded <strong>Facebook Timeline and Events</strong>, and added text about <strong>donations</strong> in the <a href="/">Home</a> page.
    - Added <strong>About Us</strong> and <strong>History</strong> sections to the <a href="/about">About Us</a> page.
    - Embedded <strong>Facebook Messages</strong>, and removed <strong>Physical Address, Office Hours, and Google Maps</strong> in the <a href="/contact">Contact Us</a> page.
    - Added <strong>Kairos photo creds and website link</strong> to the footer.
    - Added <strong>News & Events</strong> tab, which redirects to the Facebook page.
    - Added <a href="/services">Services</a> page (English only).
    - Added <a href="/programs">Programs</a> page (English only). <strong>Fixed typo of the word "individuals."</strong>
    - Added <strong>"active" indicators</strong> to the navigation menu to show which page is the one you are currently visiting.
  domain: localhost
  email: office@elpuentesearcy.org
  phone: 5018279944
  officeHoursWeekday: 9:00am - 4:00pm
  officeHoursWeekend: 1:00pm - 5:00pm
  physicalAddress:
  mailingAddress:
    - P.O. Box 8046
    - Searcy, AR 72145
  facebookUrl: https://www.facebook.com/elpuentesearcy/
  twitterUrl:
  google:
    analytics:
      trackingId:
    maps:
      apiKey: AIzaSyAUs1B95NJzFcSpf2An9EDWfKCrDyHlrwQ
  board:
    -
      name: Jay Simpson
      title:
        en: President
        es: El Presidente
      description:
        en: Senior Associate Director of Financial Aid Services<br/><strong>Harding University</strong>
    -
      name: Larry Wilks
      title:
        en: Vice President
        es: El Vicepresidente
      description:
        en: Chaplain<br/><strong>Harding Place</strong>
    -
      name: Jaclyn Seiders
      title:
        en: Secretary/Treasurer
        es: La Sectretaria-Tesorera
      description:
        en: Literacy Coach/ESOL Coordinator<br/><strong>Searcy Public Schools</strong>
    -
      name: Guillermo Hernandez
      title:
        en:
      description:
        en: Immigration Attorney<br/><strong>Hernandez Law Firm</strong>
    -
      name: Tity Abbud
      title:
        en:
      description:
        en: Community Advocate
    -
      name: Logan Russell
      title:
        en:
      description:
        en: Community Liaison<br/><strong>ARCare</strong>
    -
      name: Dr. Roddy Lochala
      title:
        en:
      description:
        en: Family Medicine Residency Associate Program Director<br/><strong>Unity Health</strong>
  staff:
    - name: Ruth Simpson
      title:
        en: Executive Director
        es: La Directora Ejecutiva
      description:
        en: